### ISSUE TITLE
BFGMiner 3.2.1 returns 400 error

### ISSUE THREAD

**Issue by ksolomon** [jedimstr/BFGMobileAdapter#1]
This is what I see when I run the script:

keith@Dev Server: ~/BFGMobileAdapter-master $ ./BFGMobileAdapter.py
[ -=-=-=-=- Starting BFGMobileAdapter - BFGMiner to MobileMiner Interface -=-=-=-=- ]
[2013-10-18 09:50:01]  Getting Data from BFGMiner RPC API using port:4028
2013-10-18 09:50:02,029 WARNING HTTPError = 400
[2013-10-18 09:50:02]  Sending to MobileMiner API from Dev Server Miner

Any ideas on what the problem is or how I can get you more info to debug it?

EDIT: I just updated to bfgminer 3.3.0 this morning, and it also returns the 400 error.

**Comment by ksolomon** [comment]
Never mind.  Problem turned out to be spaces in the machine name.  It's working great now that I fixed that.

**Comment by rinchen** [comment]
@jedimstr I had the same problem. Perhaps you can jam this in the README along with needing --api-list and --api-network
