### ISSUE TITLE
CGminer doesnt work with script

### ISSUE THREAD

**Issue by Hazado** [jedimstr/BFGMobileAdapter#2]
Here is the output json string from CGminer, That's for 4 GPU 7950's ive got running.
Hope this helps you improve the script

{u'STATUS': [{u'STATUS': u'S', u'Msg': u'4 GPU(s) - 0 ASC(s) - 0 PGA(s) - ', u'Code': 9, u'When': 1386470026, u'Description': u'cgminer 3.1.1'}], u'DEVS': [{u'Difficulty Accepted': 83032.0, u'Temperature': 76.0, u'Difficulty Rejected': 2273.0, u'GPU Voltage': 1.056, u'GPU Clock': 1100, u'Fan Speed': 1189, u'Status': u'Alive', u'Fan Percent': 37, u'Rejected': 14, u'Memory Clock': 1500, u'Hardware Errors': 0, u'Accepted': 344, u'Last Share Pool': 0, u'Diff1 Work': 97687, u'Total MH': 6285.1645, u'Enabled': u'Y', u'Last Valid Work': 1386470025, u'Last Share Time': 1386469975, u'GPU': 0, u'MHS av': 0.67, u'Last Share Difficulty': 64.0, u'MHS 5s': 0.68, u'GPU Activity': 99, u'Intensity': u'20', u'Powertune': 20, u'Utility': 2.19}, {u'Difficulty Accepted': 77799.0, u'Temperature': 74.0, u'Difficulty Rejected': 2714.0, u'GPU Voltage': 1.056, u'GPU Clock': 1100, u'Fan Speed': 1178, u'Status': u'Alive', u'Fan Percent': 24, u'Rejected': 19, u'Memory Clock': 1500, u'Hardware Errors': 0, u'Accepted': 318, u'Last Share Pool': 0, u'Diff1 Work': 88982, u'Total MH': 6251.6101, u'Enabled': u'Y', u'Last Valid Work': 1386470022, u'Last Share Time': 1386469978, u'GPU': 1, u'MHS av': 0.66, u'Last Share Difficulty': 64.0, u'MHS 5s': 0.68, u'GPU Activity': 99, u'Intensity': u'20', u'Powertune': 20, u'Utility': 2.03}, {u'Difficulty Accepted': 79152.0, u'Temperature': 74.0, u'Difficulty Rejected': 2790.0, u'GPU Voltage': 1.056, u'GPU Clock': 1100, u'Fan Speed': 1057, u'Status': u'Alive', u'Fan Percent': 19, u'Rejected': 17, u'Memory Clock': 1500, u'Hardware Errors': 0, u'Accepted': 336, u'Last Share Pool': 0, u'Diff1 Work': 95829, u'Total MH': 6226.4443, u'Enabled': u'Y', u'Last Valid Work': 1386470017, u'Last Share Time': 1386469971, u'GPU': 2, u'MHS av': 0.66, u'Last Share Difficulty': 197.0, u'MHS 5s': 0.68, u'GPU Activity': 99, u'Intensity': u'20', u'Powertune': 20, u'Utility': 2.14}, {u'Difficulty Accepted': 73320.0, u'Temperature': 70.0, u'Difficulty Rejected': 3104.0, u'GPU Voltage': 1.056, u'GPU Clock': 1100, u'Fan Speed': 1259, u'Status': u'Alive', u'Fan Percent': 29, u'Rejected': 16, u'Memory Clock': 1500, u'Hardware Errors': 0, u'Accepted': 312, u'Last Share Pool': 0, u'Diff1 Work': 93095, u'Total MH': 6183.4527, u'Enabled': u'Y', u'Last Valid Work': 1386470022, u'Last Share Time': 1386469998, u'GPU': 3, u'MHS av': 0.66, u'Last Share Difficulty': 197.0, u'MHS 5s': 0.68, u'GPU Activity': 99, u'Intensity': u'20', u'Powertune': 20, u'Utility': 1.99}], u'id': 1}

**Comment by jedimstr** [comment]
Latest git pull should fix it now.
