### ISSUE TITLE
Error on Mac

### ISSUE THREAD

**Issue by desertpilot** [jedimstr/BFGMobileAdapter#4]
I am a total novice at command line and I'm stumbling my way through this. I'm getting this error when I launch the .py file 

Last login: Wed Jan 15 00:08:12 on ttys000
cd '/Users/trevorsmith/Desktop/cgminer-3.10.0-mac-full/' && '/usr/bin/pythonw'  '/Users/trevorsmith/Desktop/cgminer-3.10.0-mac-full/BFGMobileAdapter.py'  && echo Exit status: $? && exit 1
Trevor-MacBook:~ trevorsmith$ cd '/Users/trevorsmith/Desktop/cgminer-3.10.0-mac-full/' && '/usr/bin/pythonw'  '/Users/trevorsmith/Desktop/cgminer-3.10.0-mac-full/BFGMobileAdapter.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/trevorsmith/Desktop/cgminer-3.10.0-mac-full/BFGMobileAdapter.py", line 17, in <module>
    import argparse
ImportError: No module named argparse
Trevor-MacBook:cgminer-3.10.0-mac-full trevorsmith$ 

I'm running OSX 10.6.8. I filled in the email and appKey but was unsure about the machineName right now I just have it as cgminer. 

Any help would be great.

**Comment by rinchen** [comment]
@desertpilot you might see if you have an older version of python.  http://stackoverflow.com/questions/17716257/apportable-no-module-named-argparse-error-on-mac
