### ISSUE TITLE
CurrentHashrate error

### ISSUE THREAD

**Issue by rinchen** [jedimstr/BFGMobileAdapter#5]
Hi,

On Ubuntu 14.04 with BFGMiner 4.2.0 python throws some sort of error with this line:
device[u'CurrentHashrate'] = item[u'MHS 5s'] \* 1000

If I comment it out with a # it works but obviously it doesn't report the hash rate.

**Comment by rinchen** [comment]
It seems that the key is now u'MHS 20s'

**Comment by jedimstr** [comment]
Sorry for the late reply... I haven't maintained this script for a long time and there have been quite a few changes to the BFGMiner and CGMiner API since.  You can modify the skeleton provided in this script and request a git pull for any fixes if you think others could find it useful.

**Comment by ghost** [comment]
the u'MHS 20s' did the trick.  I created a pull request as requested
